"use client"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/themeProviders";
import { Provider } from "react-redux";
import { store } from '../store'
import Sidebar from '@/components/Sidebar'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{

//   const auth= getAuth(app);
//   const navigate = useNavigate();
//   const dispatch = useDispatch();

// useEffect(() => {
//   const unsubscribe = onAuthStateChanged(auth, (user) => {  //user 정보를 가져오고 user에 auth가 바뀔때마다 실행
//     if(user) {  //로그인이 되었으며
//       navigate('/');

//       dispatch(setUser({   // 이 셋 파라미터가 이해가 안간다.??
//         uid: user.uid,
//         displayName: user.displayName,
//         photoURL: user.photoURL

//       })) //userSlice에 액션함수를 생성 후 넣어준다
//     } else {
//       navigate('/register');
//       dispatch(clearUser());
//     }
//   })

//   return () => {
//     unsubscribe();
//   }
// }, [])







  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Sidebar>
            {children}
            </Sidebar>
          </ThemeProvider>
          </Provider>
        </body>
    </html>
  );
}
